version: "3.7"
services:
  node:
    image: ghcr.io/subspace/node:gemini-1b-2022-june-02
    volumes:
      - node-data:/var/subspace:rw
    ports:
      - "0.0.0.0:30333:30333"
    restart: unless-stopped
    command:
      [
        "--chain",
        "gemini-1",
        "--base-path",
        "/var/subspace",
        "--execution",
        "wasm",
        "--pruning",
        "1024",
        "--keep-blocks",
        "1024",
        "--port",
        "30333",
        "--rpc-cors",
        "all",
        "--rpc-methods",
        "safe",
        "--unsafe-ws-external",
        "--validator",
        "--name",
        "149.102.154.179"
      ]
    healthcheck:
      timeout: 5s
      interval: 30s
      retries: 5

  farmer:
    image: ghcr.io/subspace/farmer:gemini-1b-2022-june-02
    volumes:
      - farmer-data:/var/subspace:rw
    restart: unless-stopped
    command:
      [
        "--base-path",
        "/var/subspace",
        "farm",
        "--node-rpc-url",
        "ws://node:9944",
        "--ws-server-listen-addr",
        "0.0.0.0:9955",
        "--reward-address",
        "stBA3hddVJ6fHgBtMkAcgfkpho6Zq1MhD98gSwkysHpzTLAxL",
        "--plot-size",
        "150G"
      ]
    depends_on:
      node:
        condition: service_healthy

volumes:
  node-data:
  farmer-data:
